### ISSUE TITLE
Problem with wrong version of AFNetworking being resolved via pod:update

### ISSUE THREAD

**Issue by matthewsinclair** [HipByte/motion-cocoapods#108]
I have a simple RubyMotion project app with next to nothing in it. The project depends on two gems that I have created. One of the gems has some REST stuff (`restikle`), and the other has some UIKit stuff (`tillless-uikit`). I want to include them both into the app project as gems. Both gem-based projects work fine. I can run the tests on them, as well as fire up a dummy app in each case. The `tillless-uikit` gem depends on the `restikle` gem. 

Running `bundle exec rake pod:update` in either of the gem projects works fine, with a `Podfile.lock` created and the appropriate pods downloaded and installed into `vendor/`. 

Because I am using `RestKit`, I need to specify the version of `AFNetworking` to use as `1.3.4`, which I have done in both of the gem projects, as well as the app project. The pods line in the gem project's `rakefile` look like this:

```
  # From Rakefile in 'restikle' gem project
  app.pods do
    pod 'AFNetworking', '~> 1.3.4'
    pod 'RestKit'
  end
```
```
  # From Rakefile in 'tillless-uikit' project 
  app.pods do
    pod 'AFNetworking', '~> 1.3.4'
    pod 'RestKit'
    pod 'NSData+MD5Digest'
    pod 'NSData+Base64'
    pod 'SVProgressHUD'
    pod 'JMImageCache'
    pod 'SVProgressHUD'
    pod 'TSMessages'
    pod 'ABPadLockScreen'
  end
```
And here's the same pod lines from the app project:
```
  # Rakefile in app project 
  app.pods do
    pod 'AFNetworking', '~> 1.3.4'
    # pod 'RestKit'
    # pod 'NSData+MD5Digest'
    # pod 'NSData+Base64'
    # pod 'SVProgressHUD'
    # pod 'JMImageCache'
    # pod 'SVProgressHUD'
    # pod 'TSMessages'
    # pod 'ABPadLockScreen'
  end
```
I have commented out the other pods in the app project in a (somewhat vain) attempt to get it to work. The problem is, that without that first pod entry, the app project tries to load in version `2.5` of `AFNetworking`. But with that line in place, the `bundle exec rake pod:update` command fails with the following dependency error:
```
$ bundle exec rake pod:update COCOAPODS_VERBOSE=1
  WARNING! BubbleWrap::HTTP is deprecated and will be removed, see https://github.com/rubymotion/BubbleWrap/issues/308
  WARNING! Switch to a different networking library soon - consider AFNetworking: http://afnetworking.com/
  WARNING! You can use the 'bubble-wrap-http' gem if you need compatibility: https://github.com/rubymotion/BubbleWrap-HTTP
  $ /usr/local/bin/git rev-parse  >/dev/null 2>&1

Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  Already up-to-date.
  Preparing
    Migrating to CocoaPods 0.36

Analyzing dependencies

Inspecting targets to integrate

Finding Podfile changes
  - AFNetworking

Resolving dependencies of `Rakefile`
Starting resolution (2015-01-27 16:10:16 +1100)
Creating possibility state for AFNetworking (~> 2.5) (1 remaining)
  Attempting to activate AFNetworking (2.5.0)
  Activated AFNetworking at AFNetworking (2.5.0)
  Requiring nested dependencies (AFNetworking/Serialization (= 2.5.0), AFNetworking/Security (= 2.5.0), AFNetworking/Reachability (= 2.5.0), AFNetworking/NSURLConnection (= 2.5.0), AFNetworking/NSURLSession (= 2.5.0), AFNetworking/UIKit (= 2.5.0))
  Creating possibility state for AFNetworking (~> 1.3.4) (1 remaining)
    Attempting to activate AFNetworking (1.3.4)
    Found existing spec (AFNetworking (2.5.0))
    Unsatisfied by existing spec (AFNetworking (2.5.0))
    Unwinding for conflict: AFNetworking (~> 1.3.4)
Finished resolution (2 steps) (Took 0.00917 seconds) (2015-01-27 16:10:16 +1100)
rake aborted!
Pod::Informative: [!] Unable to satisfy the following requirements:

- `AFNetworking (~> 2.5)` required by `Podfile`
- `AFNetworking (~> 1.3.4)` required by `Podfile`/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:398:in `handle_resolver_error'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:58:in `rescue in resolve'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:53:in `resolve'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:424:in `block in resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:422:in `resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:186:in `analyze'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:108:in `block in resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:107:in `resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:90:in `install!'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:225:in `install!'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:354:in `block (2 levels) in <top (required)>'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/bin/ruby_executable_hooks:15:in `eval'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/bin/ruby_executable_hooks:15:in `<main>'
Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `AFNetworking (~> 2.5)` required by `Podfile`
- `AFNetworking (~> 1.3.4)` required by `Podfile`/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:185:in `block in unwind_for_conflict'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:183:in `tap'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:183:in `unwind_for_conflict'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:325:in `attempt_to_activate_existing_spec'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:308:in `attempt_to_activate'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:139:in `process_topmost_state'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolution.rb:68:in `resolve'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/molinillo-0.2.0/lib/molinillo/resolver.rb:40:in `resolve'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/resolver.rb:55:in `resolve'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:424:in `block in resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:422:in `resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:186:in `analyze'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:108:in `block in resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:107:in `resolve_dependencies'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:90:in `install!'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:225:in `install!'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:354:in `block (2 levels) in <top (required)>'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/bin/ruby_executable_hooks:15:in `eval'
/Users/matts/.rvm/gems/ruby-2.2.0@rails4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => pod:update
(See full trace by running task with --trace)
```

This is incredibly frustrating, and is currently stopping me from moving forward. What is asking for version 0.2.5 of AFNetworking? How can I work out what is causing that? These lines two lines:

```
- `AFNetworking (~> 2.5)` required by `Podfile`
- `AFNetworking (~> 1.3.4)` required by `Podfile`
```

are not very helpful. 

Any help would be much appreciated! Thanks,
M@

PS: Cross-posted from RubyMotion groups [here](https://groups.google.com/forum/?fromgroups=#!topic/rubymotion/VymbWzpleLE).

**Comment by matthewsinclair** [comment]
Damn, I found it just after I posted this. I was including the `afmotion` gem, which by default, was looking for `AFNetworking` version `2.5`. Argh. Sorry to bother everyone.
