### ISSUE TITLE
No such file or directory - vendor/Pods/Pods-resources.sh

### ISSUE THREAD

**Issue by adammenges** [HipByte/motion-cocoapods#109]
I get this error when running my project. Seems to be similar to #98 

```
⇒  rake
rake aborted!
Errno::ENOENT: No such file or directory - vendor/Pods/Pods-resources.sh
/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.3.0.rc1/lib/motion/project/cocoapods.rb:186:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.3.0.rc1/lib/motion/project/cocoapods.rb:186:in `open'
/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.3.0.rc1/lib/motion/project/cocoapods.rb:186:in `resources'
/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.3.0.rc1/lib/motion/project/cocoapods.rb:156:in `install_resources'
/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.3.0.rc1/lib/motion/project/cocoapods.rb:121:in `link_project'
/Library/Ruby/Gems/2.0.0/gems/motion-cocoapods-1.3.0.rc1/lib/motion/project/cocoapods.rb:48:in `pods'
/Users/adammenges/Dropbox/Development/AFNetworking-RubyMotion-Example/Rakefile:13:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:115:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:115:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:115:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:115:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Library/RubyMotion/lib/motion/project/template/ios.rb:129:in `block in <top (required)>'
Tasks: TOP => default => simulator
(See full trace by running task with --trace)
```

**Comment by Watson1978** [comment]
Need more information to reproduce.
