### ISSUE TITLE
Can't build a project if it uses Pods which have static library only.

### ISSUE THREAD

**Issue by Watson1978** [HipByte/motion-cocoapods#121]
```ruby
Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'HelloAnalytics'
  app.pods do
    pod 'GoogleAnalytics-iOS-SDK'
  end
end
```

```
$ rake
...
    ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.
```

**Comment by MarkVillacampa** [comment]
This is probably because we don't add anything to he :products array in this case.

**Comment by awernick** [comment]
I don't know if this is related, but I started getting this error message today out of nowhere in all my projects. 

```
ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.
/Library/RubyMotion/lib/motion/project/vendor.rb:220:in `build_xcode'
/Library/RubyMotion/lib/motion/project/vendor.rb:48:in `block in build'
/Library/RubyMotion/lib/motion/project/vendor.rb:47:in `chdir'
/Library/RubyMotion/lib/motion/project/vendor.rb:47:in `build'
/Library/RubyMotion/lib/motion/project/builder.rb:69:in `block in build'
/Library/RubyMotion/lib/motion/project/builder.rb:68:in `each'
/Library/RubyMotion/lib/motion/project/builder.rb:68:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/awernick/.rvm/gems/ruby-2.2.1/gems/motion-cocoapods-1.6.0/lib/motion/project/cocoapods.rb:53:in `build_with_cocoapods'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/awernick/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/awernick/.rvm/gems/ruby-2.2.1/bin/rake:23:in `load'
/Users/awernick/.rvm/gems/ruby-2.2.1/bin/rake:23:in `<main>'
/Users/awernick/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/awernick/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

This error keeps popping up whenever I try to add a pod into my project file. It is project independent since any cocoapod triggers the error. As soon as I remove the pod dependency, the error disappears and the project builds correctly.

I've cleansed my project multiple times, and tried building the project in different machines with the same results.

I've also tried using a different gem version. I have tried 1.6.0 and 1.7.1.

Here is a gist of my Rakefile and Gemfile
https://gist.github.com/awernick/952d46a8aac4c0033953

I have nothing else in the project besides those two files, and the standard app_delegate.rb  boilerplate.

Also, I'm using the latest cocoapods version (0.38.2).

**Comment by awernick** [comment]
I managed to run one of my projects (without moving anything)  after cleaning the build path.
Unfortunately I get a different error that might be related:
```
Objective-C stub for message `GET:parameters:success:failure:' type `@@:@@@?@?' 
not precompiled. Make sure you properly link with the framework or library 
that defines this message.
```
I'm sure that this refers to the AFNetworking pod that I use in that project. 

Rakefile and Gemfile
https://gist.github.com/awernick/b3b560541f6164647ad6

**Comment by awernick** [comment]
I was able to fix my problems by downgrading to cocoapods version 0.36.4. Everything seems to be working correctly using this version.

**Comment by brunodp** [comment]
Hey @MarkVillacampa, that means that if I do something like:

```ruby
	app.pods products: ['FBAudienceNetwork'] do
		pod 'FBAudienceNetwork'
	end
```
it should work ? Because I'm still getting 

ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.

Same thing with Google Mobile Ads and Google Analytics.

Vendoring like:

```ruby
app.vendor_project("vendor/FBAudienceNetwork.framework", :static, products: ['FBAudienceNetwork']) does work)
```

**Comment by kb** [comment]
I'm also running into this issue with a newly generated/vanilla RM project.

```text
Kyles-MacBook-Pro ios (master #)$ bundle exec rake build --trace
** Invoke build (first_time)
** Execute build
** Invoke build (first_time)
** Invoke build:simulator (first_time)
** Execute build:simulator
rm -f ./build/iPhoneSimulator-9.1-Development/dollarbet.app/Info.plist
    ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.
/Library/RubyMotion/lib/motion/project/vendor.rb:226:in `build_xcode'
/Library/RubyMotion/lib/motion/project/vendor.rb:48:in `block in build'
/Library/RubyMotion/lib/motion/project/vendor.rb:47:in `chdir'
/Library/RubyMotion/lib/motion/project/vendor.rb:47:in `build'
/Library/RubyMotion/lib/motion/project/builder.rb:69:in `block in build'
/Library/RubyMotion/lib/motion/project/builder.rb:68:in `each'
/Library/RubyMotion/lib/motion/project/builder.rb:68:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/motion-cocoapods-1.7.7/lib/motion/project/cocoapods.rb:53:in `build_with_cocoapods'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/kyle/.rbenv/versions/2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/kyle/.rbenv/versions/2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-hooks-1.2.3/lib/rake/hooks.rb:18:in `block (2 levels) in after'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/kyle/.rbenv/versions/2.1.7/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/bin/rake:23:in `load'
/Users/kyle/.rbenv/versions/2.1.7/gemsets/documents/bin/rake:23:in `<main>'
```

Tried all solutions talked about in similar issues for " ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.", but nothing seems to fix this.

Should I attempt to downgrade cocoapods?

**Comment by kb** [comment]
@MarkVillacampa I just tried your branch out and it seems to still error for me.

Steps I took...

Changed `gem motion-cocoapods` to `gem 'motion-cocoapods', :git => 'https://github.com/HipByte/motion-cocoapods.git', :branch => 'fix-binary-pod-error'` in my Gemfile.

`bundle installed`
`rake clean:all`
`rake pod:install`
`bundle exec rake build`

Results in the follow for me. 
```text
     Build ./build/iPhoneSimulator-9.1-Development
     Build ./Pods.xcodeproj [Pods - Release]
   Compile ./Target Support Files/Pods/Pods-dummy.m
   Compile ./Target Support Files/Pods/Pods-dummy.m
      Link ./Users/kyle/Documents/motion/tester/vendor/build/Pods.build/Release-iphonesimulator/Pods.build/Objects-normal/x86_64/libPods.a
      Link ./Users/kyle/Documents/motion/tester/vendor/build/Pods.build/Release-iphonesimulator/Pods.build/Objects-normal/i386/libPods.a
    ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.
```

Perhaps I'm missing a critical step to get this patch working?

For reference I tried this in a newly created RM app.

Here's the Rakefile...

```ruby
Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'tester'

  app.pods do
    pod 'Crashlytics'
  end
end
```

**Comment by MarkVillacampa** [comment]
@kb As I said in the pull request, this requires support in RubyMotion core. We will add it in the next version. Meanwhile, you can patch your local copy of RubyMotion, since the patch is very simple:

```diff
diff --git a/lib/motion/project/vendor.rb b/lib/motion/project/vendor.rb
index def5894..e17ce16 100644
--- a/lib/motion/project/vendor.rb
+++ b/lib/motion/project/vendor.rb
@@ -216,7 +216,7 @@ EOS
       end

       @libs = Dir.glob("#{build_dir}/*.a").map { |x| File.expand_path(x) }
-      if @libs.empty?
+      if @libs.empty? && !@opts[:allow_empty_products]
         App.fail "Building vendor project `#{@path}' failed to create at least one `.a' library."
       end

```

**Comment by kb** [comment]
@MarkVillacampa Thanks for the reply. I must have missed the update to core mentioned in your PR.

Just wanted to confirm that I was able to successfully build an app by patching my local RM and running with your motion-cocoapods branch. :smile:
