### ISSUE TITLE
"uninitialized constant" with VKVikiVideoPlayer

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-cocoapods#125]
on rake file:
```
  app.pods do |pod|
    #pod 'Kickflip'
    pod "VKVideoPlayer", "~> 0.1.1"
    pod 'SDWebImage'
  end
```

on the screen:
```
  def on_load
    player = VKVikiVideoPlayer.alloc.initWithVideoPlayerView(VKVikiVideoPlayer.alloc.init)
    player.delegate = self
    rmp.append(player)
  end
```

Getting:
```
[71298:1530718] home_screen.rb:4:in `on_load': uninitialized constant HomeScreen::VKVikiVideoPlayerView (NameError)
	from screen_module.rb:37:in `view_did_load'
	from view_controller.rb:15:in `viewDidLoad'
	from delegate_module.rb:58:in `open:'
	from app_delegate.rb:9:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-11-04 10:15:27.086 Hubble[71298:1530718] home_screen.rb:4:in `on_load': uninitialized constant HomeScreen::VKVikiVideoPlayerView (NameError)
	from screen_module.rb:37:in `view_did_load'
	from view_controller.rb:15:in `viewDidLoad'
	from delegate_module.rb:58:in `open:'
	from app_delegate.rb:9:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-11-04 10:15:27.093 Hubble[71298:1530718] *** Terminating app due to uncaught exception 'NameError', reason: 'home_screen.rb:4:in `on_load': uninitialized constant HomeScreen::VKVikiVideoPlayerView (NameError)
	from screen_module.rb:37:in `view_did_load'
	from view_controller.rb:15:in `viewDidLoad'
	from delegate_module.rb:58:in `open:'
	from app_delegate.rb:9:in `on_load:'
	from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
```

Any idea why?

**Comment by MarkVillacampa** [comment]
The correct class name seems to be "VKVideoPlayer"

**Comment by hugoerg56** [comment]
you are right @MarkVillacampa thanks, now im getting:
```
[72072:1535933] -[VKVideoPlayer fullscreenButton]: unrecognized selector sent to instance 0x11439cc00
2015-11-04 10:28:57.792 Hubble[72072:1535933] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[VKVideoPlayer fullscreenButton]: unrecognized selector sent to instance 0x11439cc00'
```
but I'll see it... Thanks!
