### ISSUE TITLE
uninitialized constant AppDelegate::Kickflip (NameError)

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-cocoapods#127]
I'm trying to include the Kickflip pod but i get this error: "uninitialized constant AppDelegate::Kickflip (NameError)"

  I just add:

```
  app.pods do |pod|
    pod 'Kickflip'
```

run 'rake clean:all' and rake pod:install but i get the same error.

Any idea?

**Comment by Watson1978** [comment]
I cannot build this library.
Could you tell me how to build this library?

```
$ rake 

(snip)

   Compile ./app/app_delegate.rb
    Create ./build/iPhoneSimulator-9.1-Development/TestCocoaPods.app
      Link ./build/iPhoneSimulator-9.1-Development/TestCocoaPods.app/TestCocoaPods
ld: building for iOS simulator, but linking against dylib built for OSX, file '/usr/lib/libcrypto.dylib' for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
rake aborted!
Command failed with status (1): [/Applications/Xcode.app/Contents/Developer...]
/Library/RubyMotion4.5/lib/motion/project/builder.rb:357:in `build'
/Library/RubyMotion4.5/lib/motion/project/app.rb:78:in `build'
/Library/RubyMotion4.5/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
/Library/RubyMotion4.5/lib/motion/project/template/ios.rb:186:in `block in <top (required)>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
```

I tried to build with Xcode project too.
However, I cannot build library.

```
[~/Desktop/TestKickflip]$ cat Podfile
platform :ios, '9.0'

pod 'Kickflip'

[~/Desktop/TestKickflip]$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.6.3)
Using AFOAuth2Manager (2.2.0)
Using AWSCore (2.3.0)
Using AWSS3 (2.3.0)
Using CocoaLumberjack (1.9.2)

(snip)
```

![](http://cl.ly/image/2L17291g2A0p/151119-0001.png)

There is a problem in this library, not motion-cocoapods ?

**Comment by Watson1978** [comment]
I cannot still build `Kickflip`

```
$ rake -t
...
/Users/watson/tmp/ios/vendor/Pods/Kickflip/Kickflip/Utilities/KFAWSCredentialsProvider.h:42:4: error: expected a type
- (BFTask *)refresh;
   ^
/Users/watson/tmp/ios/vendor/Pods/Kickflip/Kickflip/Utilities/KFAWSCredentialsProvider.m:10:9: fatal error: 'Bolts/BFTask.h' file not found
#import <Bolts/BFTask.h>
        ^
2 errors generated.
...
```

Need more information to reproduce your issue.
