### ISSUE TITLE
Building vendor project `vendor/Pods' failed to create at least one `.a' library

### ISSUE THREAD

**Issue by buley** [HipByte/motion-cocoapods#135]
```
ERROR! Building vendor project `vendor/Pods' failed to create at least one `.a' library.
/Library/RubyMotion/lib/motion/project/vendor.rb:220:in `build_xcode'
/Library/RubyMotion/lib/motion/project/vendor.rb:48:in `block in build'
/Library/RubyMotion/lib/motion/project/vendor.rb:47:in `chdir'
/Library/RubyMotion/lib/motion/project/vendor.rb:47:in `build'
/Library/RubyMotion/lib/motion/project/builder.rb:69:in `block in build'
/Library/RubyMotion/lib/motion/project/builder.rb:68:in `each'
/Library/RubyMotion/lib/motion/project/builder.rb:68:in `build'
/Library/RubyMotion/lib/motion/project/app.rb:78:in `build'
/Users/buley/.rvm/gems/ruby-2.2.1/gems/motion-cocoapods-1.7.0/lib/motion/project/cocoapods.rb:53:in `build_with_cocoapods'
/Library/RubyMotion/lib/motion/project/template/ios.rb:68:in `block (2 levels) in <top (required)>'
```

Full `rake clean` followed by `rake simulator --trace`: https://gist.githubusercontent.com/buley/89018bc8c263fb146b61/raw/e12b104fe00af159e3a4031c88b14b0dbe6a8b10/gistfile1.txt

This is new to me, perhaps interesting and perhaps related to this: https://github.com/clayallsopp/afmotion/issues/72

I have attempted to solve by forcing x86_64 but I seem to be barking up the wrong tree:

>  app.archs['iPhoneOS'] << 'arm64'
>  app.archs['iPhoneSimulator'] << 'x86_64'

```
[iosapp] motion --version                                                                                                                      
4.9
[iosapp] xcodebuild -version                                                                                                                   
Xcode 7.2.1
Build version 7C1002
```

**Comment by BananaNeil** [comment]
I was running into a similar issue, and I ended up updating:
- ruby
- bundler
- cocoapods
- motion-cocoapods

And that got me past this error.
