### ISSUE TITLE
NoMethodError: undefined method `skip_repo_update=' for #<Pod::Config:0x007fdf4b2d8f70>

### ISSUE THREAD

**Issue by Bodacious** [HipByte/motion-cocoapods#137]
I'm not able to use motion-cocoapods at all with a new gem project. 

This is the backtrace I get when I try to run `rake pod:install`

```
Usage of the constant `Pod::SourcesManager` is deprecated, use `Pod::Config.instance.sources_manager` instead (called from /Users/Gavin/.rvm/gems/ruby-2.3.0/gems/motion-cocoapods-1.7.8/lib/motion/project/cocoapods.rb:359:in `block (2 levels) in <top (required)>')
Updating spec repo `master`
rake aborted!
NoMethodError: undefined method `skip_repo_update=' for #<Pod::Config:0x007fdf4b2d8f70>
/Users/Gavin/.rvm/gems/ruby-2.3.0/gems/motion-cocoapods-1.7.8/lib/motion/project/cocoapods.rb:89:in `initialize'
/Users/Gavin/.rvm/gems/ruby-2.3.0/gems/motion-cocoapods-1.7.8/lib/motion/project/cocoapods.rb:38:in `new'
/Users/Gavin/.rvm/gems/ruby-2.3.0/gems/motion-cocoapods-1.7.8/lib/motion/project/cocoapods.rb:38:in `pods'
/Users/Gavin/Code/Gems/katana_resource/Rakefile:19:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:121:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Users/Gavin/.rvm/gems/ruby-2.3.0/gems/motion-cocoapods-1.7.8/lib/motion/project/cocoapods.rb:366:in `block (2 levels) in <top (required)>'
Tasks: TOP => pod:install
(See full trace by running task with --trace)
```

My gems include:

```
Gems included by the bundle:
  * activesupport (4.2.6)
  * afmotion (2.6)
  * bundler (1.11.2)
  * claide (1.0.0)
  * cocoapods (1.0.0)
  * cocoapods-core (1.0.0)
  * cocoapods-deintegrate (1.0.0)
  * cocoapods-downloader (1.0.0)
  * cocoapods-plugins (1.0.0)
  * cocoapods-search (1.0.0)
  * cocoapods-stats (1.0.0)
  * cocoapods-trunk (1.0.0)
  * cocoapods-try (1.0.0)
  * colored (1.2)
  * escape (0.0.4)
  * fourflusher (0.3.0)
  * fuzzy_match (2.0.4)
  * i18n (0.7.0)
  * json (1.8.3)
  * katana_resource (0.1.0) <= My gem
  * minitest (5.8.4)
  * molinillo (0.4.5)
  * motion-cocoapods (1.7.8)
  * motion-require (0.2.0)
  * nap (1.1.0)
  * netrc (0.7.8)
  * rake (10.5.0)
  * thread_safe (0.3.5)
  * tzinfo (1.2.2)
  * xcodeproj (1.0.0)
```

Any ideas?

**Comment by Bodacious** [comment]
Apologies, wasn't using the latest version.

Works fine with `1.8.0`
