### ISSUE TITLE
 such file or directory - vendor/Pods/${BUILT_PRODUCTS_DIR}/Appirater.bundle

### ISSUE THREAD

**Issue by markrickert** [HipByte/motion-cocoapods#72]
Getting a strange error when trying to build my app:

``` bash
rake aborted!
No such file or directory - vendor/Pods/${BUILT_PRODUCTS_DIR}/Appirater.bundle
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:181:in `block in install_resources'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:179:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:179:in `install_resources'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:141:in `link_project'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:64:in `build_with_cocoapods'
/Library/RubyMotion/lib/motion/project/template/ios.rb:42:in `block (2 levels) in <top (required)>'
/Library/RubyMotion/lib/motion/project/template/ios.rb:55:in `block in <top (required)>'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `eval'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => build:simulator
(See full trace by running task with --trace)
```

Here's some relevant info:

``` bash
○ → ruby -v
ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-darwin12.4.0]

○ → motion -v
2.9

○ → bundler -v
-bash: bundler: command not found

○ → bundle -v
Bundler version 1.3.5
```

I tried a brand new project and it did the same thing as my app. You can see my [Gemfile.lock here](https://github.com/MohawkApps/BJCPStyleGuide/blob/master/Gemfile.lock) and my [pod definitions here](https://github.com/MohawkApps/BJCPStyleGuide/blob/master/Rakefile#L31-L39).

Please let mw know if I can provide any more information.

Here's the whole `rake --trace` stack:

``` bash
** Invoke default (first_time)
** Invoke simulator (first_time)
** Execute simulator
** Invoke build:simulator (first_time)
** Execute build:simulator
rake aborted!
No such file or directory - vendor/Pods/${BUILT_PRODUCTS_DIR}/Appirater.bundle
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/fileutils.rb:1515:in `stat'
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/fileutils.rb:1529:in `fu_each_src_dest0'
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:181:in `block in install_resources'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:179:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:179:in `install_resources'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:141:in `link_project'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/gems/motion-cocoapods-1.3.7/lib/motion/project/cocoapods.rb:64:in `build_with_cocoapods'
/Library/RubyMotion/lib/motion/project/template/ios.rb:42:in `block (2 levels) in <top (required)>'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Library/RubyMotion/lib/motion/project/template/ios.rb:55:in `block in <top (required)>'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:236:in `block in execute'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:231:in `execute'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:197:in `block in invoke_prerequisites'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:195:in `invoke_prerequisites'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:174:in `block in invoke_with_call_chain'
/Users/mrickert/.rvm/rubies/ruby-1.9.3-p327-falcon/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/task.rb:161:in `invoke'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:106:in `block in top_level'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:100:in `top_level'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon@global/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/rake:23:in `load'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/rake:23:in `<main>'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `eval'
/Users/mrickert/.rvm/gems/ruby-1.9.3-p327-falcon/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => build:simulator
```

**Comment by dushmantha** [comment]
building file list ... rsync: link_stat "/Users/Tharaka/Desktop/iosChatApp/ChatSecure-iOS/Pods/${BUILT_PRODUCTS_DIR}/Appirater.bundle" failed: No such file or directory (2)
rsync: link_stat "/Users/Tharaka/Desktop/iosChatApp/ChatSecure-iOS/Pods/${BUILT_PRODUCTS_DIR}/CPAProxy.bundle" failed: No such file or directory (2)
rsync: link_stat "/Users/Tharaka/Desktop/iosChatApp/ChatSecure-iOS/Pods/${BUILT_PRODUCTS_DIR}/HockeySDKResources.bundle" failed: No such file or directory (2)
rsync: link_stat "/Users/Tharaka/Desktop/iosChatApp/ChatSecure-iOS/Pods/${BUILT_PRODUCTS_DIR}/TUSafariActivity.bundle" failed: No such file or directory (2)
rsync: link_stat "/Users/Tharaka/Desktop/iosChatApp/ChatSecure-iOS/Pods/${BUILT_PRODUCTS_DIR}/UserVoice.bundle" failed: No such file or directory (2)
done

sent 1328 bytes  received 20 bytes  2696.00 bytes/sec
total size is 360101  speedup is 267.14
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
