### ISSUE TITLE
Not working with exensions

### ISSUE THREAD

**Issue by rromanchuk** [HipByte/motion-cocoapods#97]
Adding pods to this sameple project results in build failure https://github.com/HipByte/RubyMotionSamples/tree/master/ios/ExtensionsAndFrameworks

```
rake aborted!
Pod::Podfile::StandardError: Unsupported platform `ios-extension`. Platform must be `:ios` or `:osx`.
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/cocoapods-core-0.33.1/lib/cocoapods-core/podfile/target_definition.rb:354:in `set_platform'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/cocoapods-core-0.33.1/lib/cocoapods-core/podfile/dsl.rb:291:in `platform'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/motion-cocoapods-1.5.0/lib/motion/project/cocoapods.rb:72:in `initialize'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/motion-cocoapods-1.5.0/lib/motion/project/cocoapods.rb:38:in `new'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/motion-cocoapods-1.5.0/lib/motion/project/cocoapods.rb:38:in `pods'
/Users/ryan/.rvm/gems/ruby-2.1.0/bundler/gems/motion-hockeyapp-ffb3ca11d681/lib/motion/project/hockeyapp.rb:73:in `block in <top (required)>'
/Library/RubyMotion/lib/motion/project/config.rb:110:in `call'
/Library/RubyMotion/lib/motion/project/config.rb:110:in `block in setup'
/Library/RubyMotion/lib/motion/project/config.rb:110:in `each'
/Library/RubyMotion/lib/motion/project/config.rb:110:in `setup'
/Library/RubyMotion/lib/motion/project/app.rb:66:in `config'
/Library/RubyMotion/lib/motion/project/app.rb:74:in `setup'
/Users/ryan/.rvm/gems/ruby-2.1.0/gems/motion-reveal-0.0.1/lib/motion-reveal.rb:23:in `<top (required)>'
/Users/ryan/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
/Users/ryan/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
/Users/ryan/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
/Users/ryan/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
/Users/ryan/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
/Users/ryan/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
/Users/ryan/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
/Users/ryan/dev/frontback-ios/extensions/today-extension/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
    ERROR! Target 'extensions/today-extension' failed to build
```

**Comment by mikz** [comment]
@alloy confirmed that it works, thanks!

would be nice to have a release
